### ISSUE TITLE
A consfusion on logos assets

### ISSUE THREAD

**Issue by hanquansanren** [FelixHertlein/inv3d-generator#2]
Hi Felix,
I am now trying to generate inv3d dataset; I found you mentioned the logos can be downloaded from [here](https://data.vision.ee.ethz.ch/sagea/lld/)
But I found there are many big files in this link, like the image following:
I need clarification on which files I should download.
![image](https://github.com/FelixHertlein/inv3d-generator/assets/36793626/020bbc20-fb2d-4852-afa3-d59589489520)

**Comment by FelixHertlein** [comment]
You can use any logos you want when generating your own dataset.
We used "LLD-logo FILES-PNG" for Inv3D.

If you are interested in Inv3D, you can dowload it [here](https://felixhertlein.github.io/inv3d/#Downloads).

**Comment by hanquansanren** [comment]
Many thanks to your great contribution, I ignored this data link in github.io. I would like to cite your great art in future.
