### ISSUE TITLE
A tip for those suffering from "ImportError: cannot import name 'url_quote' from 'werkzeug.urls' "

### ISSUE THREAD

**Issue by kyle-bong** [FelixHertlein/inv3d-generator#3]
Here's a tip for those suffering from the error "ImportError: cannot import name 'url_quote' from 'werkzeug.urls'". 
It is said that for Flask version 2.0.1, Werkzeug version 2.2.2 is compatible. Try adding `Werkzeug==2.2.2` to the pip install ... in your `DockerFile`.

reference: https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr

**Comment by FelixHertlein** [comment]
Thank you very much the fix!

I added it to the Dockerfile and the setup.cfg.
