### ISSUE TITLE
how to generate meshes

### ISSUE THREAD

**Issue by hicxx** [FelixHertlein/inv3d-generator#4]
Hello, thank you for your work. I want to know how to generate meshes using resources from the doc3d dataset

**Comment by FelixHertlein** [comment]
Hi, 

the meshes we used for our Inv3D dataset were provided by the authors of the Doc3D dataset.
The Doc3D dataset itself does not contain the mesh data. 
Luckily, the authors sent them to us.

Feel free to reopen this issue if your question is not fully answered.

**Comment by hicxx** [comment]
> Hi,
> 
> the meshes we used for our Inv3D dataset were provided by the authors of the Doc3D dataset. The Doc3D dataset itself does not contain the mesh data. Luckily, the authors sent them to us.
> 
> Feel free to reopen this issue if your question is not fully answered.
Thank you for your reply~
